#!/bin/bash

fullname_="Rahul Mahajan"

emailGitHub_="aerorahul@users.noreply.github.com"
emailNOAA_="rahul.mahajan@noaa.gov"

case "$url" in
  github:*                ) name="${fullname_}"; email="${emailGitHub_}";;
  *@github.com:*          ) name="${fullname_}"; email="${emailGitHub_}";;
  *//github.com/*         ) name="${fullname_}"; email="${emailGitHub_}";;
  gerrit:*                ) name="${fullname_}"; email="${emailNOAA_}";;
  *@vlab.ncep.noaa.gov:*  ) name="${fullname_}"; email="${emailNOAA_}";;
  *//vlab.ncep.noaa.gov/* ) name="${fullname_}"; email="${emailNOAA_}";;
esac

unset fullname_
unset emailGitHub_
unset emailNOAA_
