###############################################################
# Source user-defined functions
test -e "${HOME}/.bash_functions" && source "${HOME}/.bash_functions"

###############################################################
# Set user-defined aliases

# Aliases to make sure that the copy, move, and remove programs
# ask you for confirmation. If you don't like this (i.e., if
# you know what you're doing), delete these lines.
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'

# Aliases to force cp, mv and rm without confirmation
alias cpf='cp -f'
alias mvf='mv -f'
alias rmf='rm -f'

# Commonly used aliases
alias h='history'
alias df='df -h'
alias du='du -hs'
alias grep='grep --color'
alias grpe='grep'

# Aliases used with man
alias appropos='man -k'
alias fman='nroff -man \!* | more -s'
alias fme='tbl \!* | nroff -me |more -s'

#	Aliases for ls
case $OSTYPE in
    darwin* )
        alias ls='/bin/ls -G' ;;
    linux* )
        alias ls='/bin/ls --color=auto' ;;
esac
alias l='ls -l'
alias ll='ls -l'
alias lh='ls -lh'
alias la='ls -la'
alias ld='ls -lt  | grep drw'
alias lda='ls -lat | grep drw'
alias lrt='ls -lrt'
alias lrta='ls -lart'
alias l1='ls -1'
alias l1rt='ls -1rt'
alias sl='ls'

# Aliases for changing directories
alias echopwd='echo "changing directory to ... `pwd`"'

# Aliases for applications
alias ncview='ncview -nc 32 -extra'

# Aliases for ssh
alias pivssh='ssh -A -o PKCS11Provider=/usr/lib/ssh-keychain.dylib'
alias sshx='/usr/bin/ssh -X'
alias sshy='/usr/bin/ssh -Y'
alias sshxy='/usr/bin/ssh -X -Y'

# Aliases for westeros's machines; See ~/.ssh/config for settings
alias dornelocal='ssh dorne.local'
alias dorne='ssh dorne'

# Aliases for NCCS machines (create a tunnel with tcluster.py first)
alias tdiscover='tcluster.py -m discover'
alias discover='sshxy discover'

# Aliases for SSEC machines
alias s4='sshxy s4'
alias cardinal='sshxy -t s4 ssh -XY cardinal'

# Aliases for Theia/Hera
alias jetTunnel='sshxy -q -L 11845:localhost:11845 jet'
alias jetLocal='sshxy -q jetLocal'
alias heraTunnel='sshxy -q -L 45545:localhost:45545 hera'
alias herabTunnel='sshxy -q -L 45545:localhost:45545 heraBoulder'
alias heraLocal='sshxy -q heraLocal'

# Copy to/from Theia/Hera (uses functions)
function scpToHera() { scpTo heraLocal $1 $2; }
function scpFromHera() { scpFrom heraLocal $1 $2; }
function rsyncToHera() { rsyncTo heraLocal $1 $2; }
function rsyncFromHera() { rsyncFrom heraLocal $1 $2; }

# Mount/Unmount remote directories (uses functions)
function s4_data() { remoteFS $1 s4 /data/users/rmahajan ${HOME}/Volumes/s4/rmahajan; }
function discover_home() { remoteFS $1 discover /home/rmahajan ${HOME}/Volumes/discover/rmahajan; }
function discover_nobackup() { remoteFS $1 discover /gpfsm/dnb02/rmahajan ${HOME}/Volumes/discover/nobackup/rmahajan; }
function discover_obsdev() { remoteFS $1 discover /gpfsm/dnb04/projects/p72/rmahajan ${HOME}/Volumes/discover/obsdev/rmahajan; }
function hera_home() { remoteFS $1 heraLocal /home/Rahul.Mahajan ${HOME}/Volumes/hera/home/Rahul.Mahajan; }
function hera_da() { remoteFS $1 heraLocal /scratch1/NCEPDEV/da/Rahul.Mahajan ${HOME}/Volumes/hera/scratch1/NCEPDEV/da/Rahul.Mahajan; }
function hera_global() { remoteFS $1 heraLocal /scratch1/NCEPDEV/global/Rahul.Mahajan ${HOME}/Volumes/hera/scratch1/NCEPDEV/global/Rahul.Mahajan; }
function hera_stmp1() { remoteFS $1 heraLocal /scratch1/NCEPDEV/stmp1/Rahul.Mahajan ${HOME}/Volumes/hera/scratch1/NCEPDEV/stmp1/Rahul.Mahajan; }
function hera_stmp2() { remoteFS $1 heraLocal /scratch1/NCEPDEV/stmp1/Rahul.Mahajan ${HOME}/Volumes/hera/scratch1/NCEPDEV/stmp2/Rahul.Mahajan; }
function hera_stmp3() { remoteFS $1 heraLocal /scratch2/NCEPDEV/stmp3/Rahul.Mahajan ${HOME}/Volumes/hera/scratch2/NCEPDEV/stmp3/Rahul.Mahajan; }
function hera_stmp4() { remoteFS $1 heraLocal /scratch2/NCEPDEV/stmp4/Rahul.Mahajan ${HOME}/Volumes/hera/scratch2/NCEPDEV/stmp4/Rahul.Mahajan; }

# Aliases for Git mistype and Git commands
alias gti='git'
alias gs='git status'
alias gl='git lg'
alias gm='git merge --no-commit --no-ff'
alias gc='git commit -m'
alias gd='git diff'
alias gx='git dl'

# Aliases for SVN
alias sci='svn ci'
alias sdiff='svn diff'
alias sstatus='svn status'
alias slog='svn log'
alias sadd='svn add'
alias spropset='svn propset svn:keywords "Author Id Revision Date"'
alias sup='svn up'

# Aliases and mistypes for make
alias mkae='make'
alias amke='make'
alias akme='make'
alias maek='make'

# Aliases for more and mistypes
alias more='less'
alias mroe='more'
alias lesss='less'

# Aliases for cd and mistypes
alias dc='cd'
alias xs='cd'
alias ..='cd ..'
alias ...='cd ../..'
alias owd='pwd'
alias mcd='mkcd'
alias mkd='mkcd'


# Aliases for vi, vim, gvim and their mis-typos
case $OSTYPE in
    darwin* )
        if [ -d "/Applications/MacVim.app/Contents/bin" ]; then
            # If MacVim installation exists, use it
            export PATH="/Applications/MacVim.app/Contents/bin:$PATH"
        else
            # Use Homebrew installation
            alias vim="mvim -v"
            alias gvim="mvim -g"
        fi
        alias vi='vim'
        ;;
    linux* )
        alias vi='vim'
        ;;
esac
alias vim='vi'
alias ci='vi'
alias ci='vi'
alias cim='vi'
alias ciM='vi'
alias givm='gvim'
alias gcim='gvim'
alias givM='gvim'
alias gciM='gvim'
alias gviM='gvim'
alias gvi='gvim'

# Aliases for tkcvs, tksvn and tkdiff from TwoBarleyCorns; and xxdiff
case $OSTYPE in
    darwin* )
        alias tkcvs='/Applications/TkCVS.app/Contents/MacOS/tkcvs.kit'
        alias tksvn='/Applications/TkCVS.app/Contents/MacOS/tkcvs.kit'
        alias tkdiff='/Applications/TkDiff.app/Contents/MacOS/tkdiff'
        alias xxdiff='/Applications/xxdiff.app/Contents/MacOS/xxdiff'
        ;;
esac

# Alias for diff (Use colordiff)
alias diff='colordiff'

# Alias for ps
case $OSTYPE in
    darwin* )
        alias psr='ps -U $USER -f';;
    linux )
        alias psr='ps -u $USER -f';;
esac
alias psax='ps ax | grep -v root'
alias psax='ps axo USER:20,pid,pcpu,pmem,vsz,rss,tty,stat,start,time,comm'
alias psssh='ps ax | grep ssh'
alias psSort='ps -eo pcpu,pid,user,args | sort -k 1 -r | head -16'

# Aliases for closing a terminal window
alias lo='exit'
alias eixt='exit'

# Aliases for tar
alias ltar='tar -tf'
alias ctar='tar -cf'
alias cztar='tar -czf'
alias xtar='tar -xf'
alias xztar='tar -xzf'

# Aliases for open
case $OSTYPE in
    darwin* )
        alias oepn='open'
        alias opne='open'
        ;;
esac

# Aliases for ldd
case $OSTYPE in
    darwin* )
        alias ldd='otool -L'
        ;;
esac

# Aliases for tail
alias tf='tail -f'

# Aliases for module mis-typos
alias moduel='module'
alias moudle='module'
alias lmodule='module'
alias moduele='module'

# Aliases for AWS
alias sshaws='ssh -i ${HOME}/.ssh/rmahajan-key-pair-nova.pem'
alias scpaws='scp -i ${HOME}/.ssh/rmahajan-key-pair-nova.pem'

# Aliases for wget
case $OSTYPE in
    darwin* )
        alias wget='wget --no-check-certificate'
        ;;
esac

###############################################################
